# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170311_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.Blog'),
            preserve_default=False,
        ),
    ]
